workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: 16.4
      vars:
        XCODE_PROJECT: "Ex-3/Ex-3/Ex-3.xcodeproj"
        XCODE_SCHEME: "Ex-3"
    scripts:
      - name: Install dependencies
        script: |
          # Install CocoaPods if needed
          if [ -f "Ex-3/Ex-3/Podfile" ]; then
            cd Ex-3/Ex-3
            pod install
            cd ../..
          fi
      - name: Build iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -configuration Debug \
          build
    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - your@email.com
