workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 30
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "Ex-3/Ex-3./Ex-3.xcodeproj"
        XCODE_SCHEME: "Ex-3"
      cocoapods: default
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -configuration Debug \
          build
    artifacts:
      - build/**/Build/Products/**/*.app
    triggering:
      events:
        - push
